package dbfiles

import "embed"

// Migrations holds the SQL files generated by `atlas migrate diff`. The glob
// also picks up .gitkeep and atlas.sum, which golang-migrate skips.
//
//go:embed migrations/*
var Migrations embed.FS
