// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO "Link" (id, token, name, "maxUploads", "uploadCount", "expiresAt", "expireAfterFirstUpload", "userId")
VALUES ($1, $2, $3, $4, 0, $5, $6, $7)
RETURNING id, token, name, "maxUploads", "uploadCount", "expiresAt", "expireAfterFirstUpload", "userId", "createdAt", "updatedAt"
`

type CreateLinkParams struct {
	ID                     pgtype.UUID      `json:"id"`
	Token                  string           `json:"token"`
	Name                   *string          `json:"name"`
	MaxUploads             int32            `json:"maxUploads"`
	ExpiresAt              pgtype.Timestamp `json:"expiresAt"`
	ExpireAfterFirstUpload bool             `json:"expireAfterFirstUpload"`
	UserId                 pgtype.UUID      `json:"userId"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.ID,
		arg.Token,
		arg.Name,
		arg.MaxUploads,
		arg.ExpiresAt,
		arg.ExpireAfterFirstUpload,
		arg.UserId,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Name,
		&i.MaxUploads,
		&i.UploadCount,
		&i.ExpiresAt,
		&i.ExpireAfterFirstUpload,
		&i.UserId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementUserLinkCount = `-- name: IncrementUserLinkCount :exec
UPDATE "User"
SET "linkCount" = "linkCount" + 1
WHERE id = $1
`

func (q *Queries) IncrementUserLinkCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementUserLinkCount, id)
	return err
}

const resetUserLinkCount = `-- name: ResetUserLinkCount :exec
UPDATE "User"
SET "linkCount" = 1, "linkCountExpireAt" = $2
WHERE id = $1
`

type ResetUserLinkCountParams struct {
	ID                pgtype.UUID      `json:"id"`
	LinkCountExpireAt pgtype.Timestamp `json:"linkCountExpireAt"`
}

func (q *Queries) ResetUserLinkCount(ctx context.Context, arg ResetUserLinkCountParams) error {
	_, err := q.db.Exec(ctx, resetUserLinkCount, arg.ID, arg.LinkCountExpireAt)
	return err
}
