// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeletedStatus string

const (
	DeletedStatusPENDING DeletedStatus = "PENDING"
	DeletedStatusDELETED DeletedStatus = "DELETED"
	DeletedStatusFAILED  DeletedStatus = "FAILED"
)

func (e *DeletedStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeletedStatus(s)
	case string:
		*e = DeletedStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeletedStatus: %T", src)
	}
	return nil
}

type NullDeletedStatus struct {
	DeletedStatus DeletedStatus `json:"DeletedStatus"`
	Valid         bool          `json:"valid"` // Valid is true if DeletedStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeletedStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeletedStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeletedStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeletedStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeletedStatus), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusACTIVE    SubscriptionStatus = "ACTIVE"
	SubscriptionStatusINACTIVE  SubscriptionStatus = "INACTIVE"
	SubscriptionStatusCANCELLED SubscriptionStatus = "CANCELLED"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"SubscriptionStatus"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type DeletedFile struct {
	ID        pgtype.UUID      `json:"id"`
	FileId    pgtype.UUID      `json:"fileId"`
	LinkId    pgtype.UUID      `json:"linkId"`
	FileUrl   string           `json:"fileUrl"`
	Status    DeletedStatus    `json:"status"`
	DeletedAt pgtype.Timestamp `json:"deletedAt"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type File struct {
	ID           pgtype.UUID      `json:"id"`
	Url          string           `json:"url"`
	Name         string           `json:"name"`
	Size         int64            `json:"size"`
	KeyUsed      bool             `json:"keyUsed"`
	UploadLinkId pgtype.UUID      `json:"uploadLinkId"`
	UserId       pgtype.UUID      `json:"userId"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

type Link struct {
	ID                     pgtype.UUID      `json:"id"`
	Token                  string           `json:"token"`
	Name                   *string          `json:"name"`
	MaxUploads             int32            `json:"maxUploads"`
	UploadCount            int32            `json:"uploadCount"`
	ExpiresAt              pgtype.Timestamp `json:"expiresAt"`
	ExpireAfterFirstUpload bool             `json:"expireAfterFirstUpload"`
	UserId                 pgtype.UUID      `json:"userId"`
	CreatedAt              pgtype.Timestamp `json:"createdAt"`
	UpdatedAt              pgtype.Timestamp `json:"updatedAt"`
}

type Subscription struct {
	ID        pgtype.UUID         `json:"id"`
	UserId    pgtype.UUID         `json:"userId"`
	PlanName  string              `json:"planName"`
	Price     float64             `json:"price"`
	Status    *SubscriptionStatus `json:"status"`
	StartDate pgtype.Timestamp    `json:"startDate"`
	EndDate   pgtype.Timestamp    `json:"endDate"`
	CancelAt  pgtype.Timestamp    `json:"cancelAt"`
	CreatedAt pgtype.Timestamp    `json:"createdAt"`
	UpdatedAt pgtype.Timestamp    `json:"updatedAt"`
}

type SubscriptionLog struct {
	ID             pgtype.UUID      `json:"id"`
	EventType      string           `json:"eventType"`
	Status         string           `json:"status"`
	UserEmail      string           `json:"userEmail"`
	UserId         pgtype.UUID      `json:"userId"`
	PaymentId      string           `json:"paymentId"`
	SubscriptionId *string          `json:"subscriptionId"`
	Amount         int32            `json:"amount"`
	Currency       string           `json:"currency"`
	RawPayload     []byte           `json:"rawPayload"`
	Message        string           `json:"message"`
	Error          *string          `json:"error"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
}

type User struct {
	ID                pgtype.UUID      `json:"id"`
	Email             *string          `json:"email"`
	Name              *string          `json:"name"`
	Username          string           `json:"username"`
	Passoword         *string          `json:"passoword"`
	Avatar            *string          `json:"avatar"`
	LinkCount         int32            `json:"linkCount"`
	LinkCountExpireAt pgtype.Timestamp `json:"linkCountExpireAt"`
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
}
