// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetUserByUsername(ctx context.Context, username string) (User, error)
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
