// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO "Session" (id, "userId", "tokenHash", "expiresAt")
VALUES ($1, $2, $3, $4)
RETURNING id, "userId", "tokenHash", "expiresAt", "revokedAt", "createdAt"
`

type CreateSessionParams struct {
	ID        pgtype.UUID      `json:"id"`
	UserId    pgtype.UUID      `json:"userId"`
	TokenHash string           `json:"tokenHash"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserId,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, "userId", "tokenHash", "expiresAt", "revokedAt", "createdAt" FROM "Session"
WHERE "tokenHash" = $1
  AND "revokedAt" IS NULL
  AND "expiresAt" > now()
LIMIT 1
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenhash string) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, tokenhash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE "Session"
SET "revokedAt" = now()
WHERE "tokenHash" = $1 AND "revokedAt" IS NULL
`

// Logout keeps the row as a login record and marks it revoked.
func (q *Queries) RevokeSession(ctx context.Context, tokenhash string) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenhash)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE "Session"
SET "revokedAt" = now()
WHERE "userId" = $1 AND "revokedAt" IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userid)
	return err
}
