// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO "Subscription" (id, "userId", "planName")
VALUES ($1, $2, $3)
RETURNING id, "userId", "planName", price, status, "startDate", "endDate", "cancelAt", "createdAt", "updatedAt"
`

type CreateSubscriptionParams struct {
	ID       pgtype.UUID `json:"id"`
	UserId   pgtype.UUID `json:"userId"`
	PlanName string      `json:"planName"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.ID, arg.UserId, arg.PlanName)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PlanName,
		&i.Price,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CancelAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
