// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, name, username, passoword, avatar, "linkCount", "linkCountExpireAt", "createdAt", "updatedAt" FROM "User"
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.Passoword,
		&i.Avatar,
		&i.LinkCount,
		&i.LinkCountExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
